# Generated by Django 4.2.13 on 2024-05-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('custom_create_application', 'Can Create Application'), ('custom_view_report', 'Can View Reports'), ('custom_system_admin', 'Is System Administratior')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
