# Generated by Django 4.2.13 on 2024-05-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_password2_user_password1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
    ]
