# Generated by Django 4.2.13 on 2024-05-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_password1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='place_of_birth',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
