# Generated by Django 4.2.13 on 2024-05-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'permissions': [('custom_create_rank', 'Can Create Rank')], 'verbose_name': 'Rank', 'verbose_name_plural': 'Ranks'},
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gps',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='authentication.grade'),
        ),
    ]
