# Generated by Django 4.2.13 on 2024-05-12 20:43

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_historicalcvhistory_cvhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attachment',
            field=models.FileField(null=True, upload_to='documents/', validators=[authentication.validators.validate_file_extension]),
        ),
    ]
