# Generated by Django 4.2.13 on 2024-05-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_user_acca_user_cima_user_degree_user_doctorate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='acca',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cima',
        ),
        migrations.RemoveField(
            model_name='user',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='doctorate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ica',
        ),
        migrations.RemoveField(
            model_name='user',
            name='masters',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other',
        ),
    ]
