# Generated by Django 4.2.13 on 2024-05-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_user_acca_remove_user_cima_remove_user_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofessionalhistory',
            name='level',
            field=models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], max_length=50),
        ),
        migrations.AlterField(
            model_name='professionalhistory',
            name='level',
            field=models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], max_length=50),
        ),
    ]
