# Generated by Django 4.2.13 on 2024-05-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_workhistory_historicalworkhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkhistory',
            name='position',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='position',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkhistory',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkhistory',
            name='startdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
